name: iOS CI - Build & Test (MyCICD)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build App (iOS Simulator Only)
        run: |
          set -o pipefail
          xcodebuild clean build \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator'

      - name: Run Tests (iOS Simulator Only)
        run: |
          set -o pipefail
          xcodebuild test \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator'
