name: iOS CI - Build & Test (MyCICD)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Build App
        run: |
          set -o pipefail
          xcodebuild clean build \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Run Tests
        run: |
          set -o pipefail
          xcodebuild test \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14'
