name: iOS CI - Build & Test (MyCICD)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build
      - name: Build MyCICD
        run: |
          set -o pipefail
          xcodebuild clean build \
            -scheme "MyCICD" \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator'

      
