name: iOS CI - Build & Test (MyCICD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:

      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Select Xcode
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Step 3: Build the app
      - name: Build MyCICD App
        run: |
          xcodebuild clean build \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15'

      # Step 4: Run Unit Tests
      - name: Run Tests
        run: |
          xcodebuild test \
          -scheme "MyCICD" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15'
